version: '3.8'

services:
    frontend:
        build:
            context: ./recommender-ui
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=production
        env_file:
            - ./recommender-ui/.env.local
        networks:
            - app-network

    backend:
        build:
            context: ./recommender-be
            dockerfile: Dockerfile
        env_file:
            - ./recommender-be/.env
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        ports:
            - '80:80'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - frontend
            - backend
        networks:
            - app-network

    db:
        image: pgvector/pgvector:pg16
        environment:
            POSTGRES_DB: movie_recommendation
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./recommender-be/db/init-pgvector.sql:/docker-entrypoint-initdb.d/init-pgvector.sql
        networks:
            - app-network

volumes:
    postgres_data:

networks:
    app-network:
        driver: bridge
